export function flattenTrnsfrmPattern(pattern: any, presets: any): string;
export function getUrlFromObj(obj: any, config: any): string;
export function getObjFromUrl(url: any, config: any, flatten: any): {
    baseUrl: string;
    filePath: any;
    pattern: any;
    version: string;
    zone: any;
    cloudName: any;
    worker: boolean;
    workerPath: string;
    options: {};
};
export function getUnArchivedPresets(presets: any): any;
export function rgbHex(red: any, green: any, blue: any, alpha: any): string;
export function getPatternFromTransformations(transformationList: any, config: any): any;
export function getPartsFromUrl(url: any, config: any): {
    baseUrl: string;
    filePath: any;
    pattern: any;
    version: string;
    zone: any;
    cloudName: any;
    worker: boolean;
    workerPath: string;
    options: {};
};
export function isPreset(ele: string): boolean;
export function checkPresetOnly(pattern: string): boolean;
export function processParams(config: any, params: any, transformation: any, paramIdMap: any, param: any, idx: any): void;
